#!/bin/bash
# 🚀 INICIO RÁPIDO - Backend API

echo "
╔════════════════════════════════════════════════════════════════╗
║                  BACKEND API - INICIO RÁPIDO                   ║
║                                                                ║
║  API para recibir datos de estabilidad de Raspberry Pi        ║
╚════════════════════════════════════════════════════════════════╝
"

echo "✨ PASO 1: Instalar dependencias del servidor"
echo "─────────────────────────────────────────────"
echo "cd server && npm install"
echo ""

echo "✨ PASO 2: Iniciar con Docker"
echo "─────────────────────────────"
echo "docker-compose up -d"
echo ""

echo "✨ PASO 3: Verificar que está corriendo"
echo "──────────────────────────────────────"
echo "docker-compose ps"
echo "curl http://localhost:5876/api/health"
echo ""

echo "✨ PASO 4: Enviar datos de prueba"
echo "─────────────────────────────────"
echo "bash server/test-api.sh http://localhost:5876"
echo ""

echo "✨ PASO 5: Consultar datos guardados"
echo "────────────────────────────────────"
echo "curl http://localhost:5876/api/stats | jq ."
echo ""

echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "📖 DOCUMENTACIÓN IMPORTANTE"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "  1. BACKEND_SUMMARY.md     ← LEER PRIMERO (Resumen completo)"
echo "  2. BACKEND_QUICKSTART.md  ← Guía de inicio rápido"
echo "  3. CLOUDFLARE_SETUP.md    ← Cómo desplegar en producción"
echo "  4. server/README.md       ← Documentación técnica del API"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo ""
echo "⚙️ CONFIGURAR RASPBERRY PI"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "Edita config.yaml en tu Raspberry Pi:"
echo ""
echo "  device_id: 'sim_rpi_001'"
echo "  api_url: 'http://tu-ip-o-dominio:5876/api/stability'"
echo "  send_interval: 5"
echo "  max_retries: 3"
echo ""
echo "Ver ejemplo en: server/example-rpi-config.yaml"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo ""
echo "📊 ENDPOINTS DISPONIBLES"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "  POST /api/stability"
echo "    → Recibir datos desde Raspberry Pi"
echo ""
echo "  GET /api/health"
echo "    → Health check"
echo ""
echo "  GET /api/stability/:device_id"
echo "    → Ver historial de un dispositivo"
echo ""
echo "  GET /api/stats"
echo "    → Ver estadísticas de todos los dispositivos"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo ""
echo "🆘 TROUBLESHOOTING"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "¿Los contenedores no inician?"
echo "$ docker-compose down"
echo "$ docker-compose up -d --build"
echo ""
echo "¿Ver logs de la API?"
echo "$ docker-compose logs -f api"
echo ""
echo "¿Ver logs de Nginx?"
echo "$ docker-compose logs -f web"
echo ""

echo "═════════════════════════════════════════════════════════════"
echo "✅ Setup completado. Lee BACKEND_SUMMARY.md para más detalles"
echo "═════════════════════════════════════════════════════════════"
